import { useSession } from "next-auth/react";
import dynamic from "next/dynamic";
import Head from "next/head";
import { Suspense } from "react";
import ShelfBookGridDB from "../../components/shelf/ShelfBookGridDB";

const ShelfBookGridLS = dynamic(
  () => import("../../components/shelf/ShelfBookGridLS"),
  {
    ssr: false,
  }
);

export default function Shelf() {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>My Shelf - fragment</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto mt-6 grid max-w-sm sm:max-w-2xl">
        <h1 className="mb-10 text-center text-2xl">My Shelf</h1>
        {!sessionData || !sessionData.user ? (
          <Suspense fallback={`Loading...`}>
            <ShelfBookGridLS />
          </Suspense>
        ) : (
          <ShelfBookGridDB />
        )}
      </div>
    </>
  );
}
