import Head from 'next/head';

export default function Shelf() {
  return (
    <>
      <Head>
          <title>My Shelf - fragment</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      <div className="mt-16 mx-auto max-w-sm sm:max-w-2xl grid">
        <h1 className="text-center mb-10 text-2xl">My Shelf</h1>
        <h2 className="text-center">EMPTY</h2>
      </div>
    </>
  );
}
